blank_issues_enabled: false

contact_links:
  - name: Questions & Discussions
    url: https://github.com/lin-stephanie/astro-antfustyle-theme/discussions
    about: Use GitHub Discussions for message-board style questions and discussions
